// Generated by scripts/generate-tetrio-firepower-snapshots.ts. Do not edit by hand.

export const TETRIO_FIREPOWER_SNAPSHOT = {
  source: {
    asset: "https://tetr.io/js/tetrio.js?hv=7eebfc9cd.987f91854aad.20260504T210001",
    lastModified: "Fri, 15 May 2026 05:42:44 GMT",
    tlOptions: {
      spinbonuses: "all-mini+",
      kickset: "SRS+",
      combotable: "multiplier",
      b2bchaining: false,
      b2bcharging: true,
      b2bextras: false,
      b2bcharge_at: 4,
      b2bcharge_base: 0,
      allclear_garbage: 5,
      allclear_b2b: 1,
      allclear_b2b_sends: false,
      allclear_b2b_dupes: true,
      allclear_charges: false,
      garbagemultiplier: 1,
      garbagespecialbonus: true,
      roundmode: "down",
      openerphase: 14
    },
    generator: "scripts/generate-tetrio-firepower-snapshots.ts"
  },
  cases: [
    {
      name: "tl-single-all-clear-uses-5-garbage-and-b2b-credit",
      events: [
        {
          clearName: "SINGLE",
          allClear: true
        }
      ],
      expected: {
        attack: 5,
        points: 3600,
        combo: 1,
        maxCombo: 1,
        backToBackChain: 1,
        allClears: 1,
        difficultClears: 0,
        difficultAttack: 0,
        spinClears: 0,
        spinAttack: 0,
        tSpinClears: 0,
        tSpinAttack: 0,
        events: [
          {
            clearName: "SINGLE",
            attack: 5,
            baseAttack: 0,
            points: 3600,
            combo: 1,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: true,
            allClearBonus: 5
          }
        ]
      }
    },
    {
      name: "tl-mini-spin-line-clears-advance-b2b",
      events: [
        {
          clearName: "TSPIN_MINI_SINGLE"
        },
        {
          clearName: "TSPIN_MINI_SINGLE"
        }
      ],
      expected: {
        attack: 1,
        points: 550,
        combo: 2,
        maxCombo: 2,
        backToBackChain: 2,
        allClears: 0,
        difficultClears: 2,
        difficultAttack: 1,
        spinClears: 2,
        spinAttack: 1,
        tSpinClears: 2,
        tSpinAttack: 1,
        events: [
          {
            clearName: "TSPIN_MINI_SINGLE",
            attack: 0,
            baseAttack: 0,
            points: 200,
            combo: 1,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_MINI_SINGLE",
            attack: 1,
            baseAttack: 0,
            points: 350,
            combo: 2,
            backToBackChain: 2,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          }
        ]
      }
    },
    {
      name: "tl-flat-b2b-bonus-does-not-grow-with-chain-when-b2bchaining-is-off",
      events: [
        {
          clearName: "TSPIN_DOUBLE"
        },
        {
          clearName: "TSPIN_DOUBLE"
        },
        {
          clearName: "TSPIN_DOUBLE"
        },
        {
          clearName: "TSPIN_DOUBLE"
        },
        {
          clearName: "TSPIN_DOUBLE"
        }
      ],
      expected: {
        attack: 35,
        points: 8900,
        combo: 5,
        maxCombo: 5,
        backToBackChain: 5,
        allClears: 0,
        difficultClears: 5,
        difficultAttack: 35,
        spinClears: 5,
        spinAttack: 35,
        tSpinClears: 5,
        tSpinAttack: 35,
        events: [
          {
            clearName: "TSPIN_DOUBLE",
            attack: 4,
            baseAttack: 4,
            points: 1200,
            combo: 1,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_DOUBLE",
            attack: 6,
            baseAttack: 4,
            points: 1850,
            combo: 2,
            backToBackChain: 2,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_DOUBLE",
            attack: 7,
            baseAttack: 4,
            points: 1900,
            combo: 3,
            backToBackChain: 3,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_DOUBLE",
            attack: 8,
            baseAttack: 4,
            points: 1950,
            combo: 4,
            backToBackChain: 4,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_DOUBLE",
            attack: 10,
            baseAttack: 4,
            points: 2000,
            combo: 5,
            backToBackChain: 5,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          }
        ]
      }
    },
    {
      name: "tl-difficult-all-clear-adds-all-clear-b2b-before-scoring",
      events: [
        {
          clearName: "TSPIN_DOUBLE",
          allClear: true
        }
      ],
      expected: {
        attack: 10,
        points: 5300,
        combo: 1,
        maxCombo: 1,
        backToBackChain: 2,
        allClears: 1,
        difficultClears: 1,
        difficultAttack: 10,
        spinClears: 1,
        spinAttack: 10,
        tSpinClears: 1,
        tSpinAttack: 10,
        events: [
          {
            clearName: "TSPIN_DOUBLE",
            attack: 10,
            baseAttack: 4,
            points: 5300,
            combo: 1,
            backToBackChain: 2,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: true,
            allClearBonus: 5
          }
        ]
      }
    },
    {
      name: "tl-b2b-charge-releases-when-chain-breaks-after-threshold",
      events: [
        {
          clearName: "QUAD"
        },
        {
          clearName: "QUAD"
        },
        {
          clearName: "QUAD"
        },
        {
          clearName: "QUAD"
        },
        {
          clearName: "QUAD"
        },
        {
          clearName: "SINGLE"
        }
      ],
      expected: {
        attack: 37,
        points: 6450,
        combo: 6,
        maxCombo: 6,
        backToBackChain: 0,
        allClears: 0,
        difficultClears: 5,
        difficultAttack: 35,
        spinClears: 0,
        spinAttack: 0,
        tSpinClears: 0,
        tSpinAttack: 0,
        events: [
          {
            clearName: "QUAD",
            attack: 4,
            baseAttack: 4,
            points: 800,
            combo: 1,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "QUAD",
            attack: 6,
            baseAttack: 4,
            points: 1250,
            combo: 2,
            backToBackChain: 2,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "QUAD",
            attack: 7,
            baseAttack: 4,
            points: 1300,
            combo: 3,
            backToBackChain: 3,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "QUAD",
            attack: 8,
            baseAttack: 4,
            points: 1350,
            combo: 4,
            backToBackChain: 4,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "QUAD",
            attack: 10,
            baseAttack: 4,
            points: 1400,
            combo: 5,
            backToBackChain: 5,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "SINGLE",
            attack: 2,
            baseAttack: 0,
            points: 350,
            combo: 6,
            backToBackChain: 0,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 1,
            allClear: false,
            allClearBonus: 0
          }
        ]
      }
    },
    {
      name: "tl-no-line-events-preserve-b2b-and-break-combo",
      events: [
        {
          clearName: "TSPIN_DOUBLE"
        },
        {
          clearName: "NONE"
        },
        {
          clearName: "TSPIN_DOUBLE"
        }
      ],
      expected: {
        attack: 9,
        points: 3000,
        combo: 1,
        maxCombo: 1,
        backToBackChain: 2,
        allClears: 0,
        difficultClears: 2,
        difficultAttack: 9,
        spinClears: 2,
        spinAttack: 9,
        tSpinClears: 2,
        tSpinAttack: 9,
        events: [
          {
            clearName: "TSPIN_DOUBLE",
            attack: 4,
            baseAttack: 4,
            points: 1200,
            combo: 1,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "NONE",
            attack: 0,
            baseAttack: 0,
            points: 0,
            combo: 0,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_DOUBLE",
            attack: 5,
            baseAttack: 4,
            points: 1800,
            combo: 1,
            backToBackChain: 2,
            backToBack: true,
            backToBackBonus: 1,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          }
        ]
      }
    },
    {
      name: "tl-ordinary-line-clear-resets-b2b-after-scoring",
      events: [
        {
          clearName: "TSPIN_DOUBLE"
        },
        {
          clearName: "SINGLE"
        },
        {
          clearName: "TSPIN_DOUBLE"
        }
      ],
      expected: {
        attack: 10,
        points: 2650,
        combo: 3,
        maxCombo: 3,
        backToBackChain: 1,
        allClears: 0,
        difficultClears: 2,
        difficultAttack: 10,
        spinClears: 2,
        spinAttack: 10,
        tSpinClears: 2,
        tSpinAttack: 10,
        events: [
          {
            clearName: "TSPIN_DOUBLE",
            attack: 4,
            baseAttack: 4,
            points: 1200,
            combo: 1,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "SINGLE",
            attack: 0,
            baseAttack: 0,
            points: 150,
            combo: 2,
            backToBackChain: 0,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          },
          {
            clearName: "TSPIN_DOUBLE",
            attack: 6,
            baseAttack: 4,
            points: 1300,
            combo: 3,
            backToBackChain: 1,
            backToBack: false,
            backToBackBonus: 0,
            backToBackChargeAttack: 0,
            allClear: false,
            allClearBonus: 0
          }
        ]
      }
    }
  ]
} as const;
