// Generated by scripts/generate-tetrio-tables.ts. Do not edit by hand.
#![allow(dead_code)]

#[derive(Clone, Copy, Eq, PartialEq)]
#[repr(usize)]
pub(crate) enum ClearKind {
    None = 0,
    Single = 1,
    Double = 2,
    Triple = 3,
    Quad = 4,
    Penta = 5,
    TSpin = 6,
    TSpinMini = 7,
    TSpinMiniSingle = 8,
    TSpinSingle = 9,
    TSpinMiniDouble = 10,
    TSpinDouble = 11,
    TSpinMiniTriple = 12,
    TSpinTriple = 13,
    TSpinMiniQuad = 14,
    TSpinQuad = 15,
    TSpinPenta = 16,
}

#[derive(Clone, Copy, Eq, PartialEq)]
pub(crate) enum ComboTable {
    Multiplier,
    None,
    ClassicGuideline,
    ModernGuideline,
}

pub const SOURCE_ASSET: &str =
    "https://tetr.io/js/tetrio.js?hv=7eebfc9cd.987f91854aad.20260504T210001";
pub const SOURCE_FETCHED_AT: &str = "2026-05-14T07:32:32+09:00";
pub const SOURCE_LAST_MODIFIED: &str = "Thu, 14 May 2026 06:42:10 GMT";

pub const BACK_TO_BACK_SCORE_MULTIPLIER: f64 = 1.5_f64;
pub const BACK_TO_BACK_BONUS: f64 = 1.0_f64;
pub const BACK_TO_BACK_BONUS_LOG: f64 = 0.8_f64;
pub const COMBO_SCORE: u32 = 50_u32;
pub const COMBO_BONUS: f64 = 0.25_f64;
pub const COMBO_MINIFIER: f64 = 1.0_f64;
pub const COMBO_MINIFIER_LOG: f64 = 1.25_f64;
pub const ALL_CLEAR_ATTACK: u32 = 10_u32;
pub const ALL_CLEAR_POINTS: u32 = 3500_u32;

pub(crate) const CLEAR_KIND_COUNT: usize = 17;
pub(crate) const CLEAR_NAMES: [&str; CLEAR_KIND_COUNT] = [
    "NONE",
    "SINGLE",
    "DOUBLE",
    "TRIPLE",
    "QUAD",
    "PENTA",
    "TSPIN",
    "TSPIN_MINI",
    "TSPIN_MINI_SINGLE",
    "TSPIN_SINGLE",
    "TSPIN_MINI_DOUBLE",
    "TSPIN_DOUBLE",
    "TSPIN_MINI_TRIPLE",
    "TSPIN_TRIPLE",
    "TSPIN_MINI_QUAD",
    "TSPIN_QUAD",
    "TSPIN_PENTA",
];
pub(crate) const CLEAR_ATTACK: [u32; CLEAR_KIND_COUNT] = [
    0_u32, 0_u32, 1_u32, 2_u32, 4_u32, 5_u32, 0_u32, 0_u32, 0_u32, 2_u32, 1_u32, 4_u32, 2_u32,
    6_u32, 4_u32, 10_u32, 12_u32,
];
pub(crate) const CLEAR_POINTS: [u32; CLEAR_KIND_COUNT] = [
    0_u32, 100_u32, 300_u32, 500_u32, 800_u32, 1200_u32, 400_u32, 100_u32, 200_u32, 800_u32,
    400_u32, 1200_u32, 800_u32, 1600_u32, 1600_u32, 2600_u32, 3200_u32,
];
pub(crate) const CLEAR_CLEARED_LINES: [u32; CLEAR_KIND_COUNT] = [
    0_u32, 1_u32, 2_u32, 3_u32, 4_u32, 5_u32, 0_u32, 0_u32, 1_u32, 1_u32, 2_u32, 2_u32, 3_u32,
    3_u32, 4_u32, 4_u32, 5_u32,
];
pub(crate) const CLEAR_BACK_TO_BACK: [bool; CLEAR_KIND_COUNT] = [
    false, false, false, false, true, true, false, false, false, true, false, true, false, true,
    true, true, true,
];

pub(crate) const COMBO_TABLE_NONE: [u32; 1] = [0_u32];
pub(crate) const COMBO_TABLE_CLASSIC_GUIDELINE: [u32; 11] = [
    0_u32, 1_u32, 1_u32, 2_u32, 2_u32, 3_u32, 3_u32, 4_u32, 4_u32, 4_u32, 5_u32,
];
pub(crate) const COMBO_TABLE_MODERN_GUIDELINE: [u32; 13] = [
    0_u32, 1_u32, 1_u32, 2_u32, 2_u32, 2_u32, 3_u32, 3_u32, 3_u32, 3_u32, 3_u32, 3_u32, 4_u32,
];

pub(crate) fn clear_kind_name(kind: ClearKind) -> &'static str {
    CLEAR_NAMES[clear_kind_index(kind)]
}

pub(crate) fn clear_kind_attack(kind: ClearKind) -> u32 {
    CLEAR_ATTACK[clear_kind_index(kind)]
}

pub(crate) fn clear_kind_points(kind: ClearKind) -> u32 {
    CLEAR_POINTS[clear_kind_index(kind)]
}

pub(crate) fn clear_kind_cleared_lines(kind: ClearKind) -> u32 {
    CLEAR_CLEARED_LINES[clear_kind_index(kind)]
}

pub(crate) fn is_back_to_back_clear(kind: ClearKind) -> bool {
    CLEAR_BACK_TO_BACK[clear_kind_index(kind)]
}

pub(crate) fn combo_table_key(table: ComboTable) -> &'static str {
    match table {
        ComboTable::Multiplier => "multiplier",
        ComboTable::None => "none",
        ComboTable::ClassicGuideline => "classic guideline",
        ComboTable::ModernGuideline => "modern guideline",
    }
}

pub(crate) fn combo_table_from_key(key: &str) -> Option<ComboTable> {
    match key {
        "multiplier" => Some(ComboTable::Multiplier),
        "none" => Some(ComboTable::None),
        "classic guideline" => Some(ComboTable::ClassicGuideline),
        "modern guideline" => Some(ComboTable::ModernGuideline),
        _ => None,
    }
}

pub(crate) fn combo_table_attack(table: ComboTable, base_attack: f64, combo: u32) -> f64 {
    match table {
        ComboTable::Multiplier => multiplier_combo_attack(base_attack, combo),
        _ => base_attack + f64::from(combo_table_attack_bonus(table, combo)),
    }
}

pub(crate) fn combo_table_attack_bonus(table: ComboTable, combo: u32) -> u32 {
    if combo <= 1 {
        return 0;
    }
    let table: &[u32] = match table {
        ComboTable::Multiplier => return 0,
        ComboTable::None => &COMBO_TABLE_NONE,
        ComboTable::ClassicGuideline => &COMBO_TABLE_CLASSIC_GUIDELINE,
        ComboTable::ModernGuideline => &COMBO_TABLE_MODERN_GUIDELINE,
    };
    let index = usize::min((combo - 2) as usize, table.len() - 1);
    table[index]
}

pub(crate) fn multiplier_combo_attack(base_attack: f64, combo: u32) -> f64 {
    if combo <= 1 {
        return base_attack;
    }
    let combo_index = (combo - 1) as f64;
    let multiplied = base_attack * (1.0 + COMBO_BONUS * combo_index);
    if combo <= 2 {
        return multiplied;
    }
    let minified = (COMBO_MINIFIER * combo_index * COMBO_MINIFIER_LOG).ln_1p();
    multiplied.max(minified)
}

fn clear_kind_index(kind: ClearKind) -> usize {
    kind as usize
}
